#include <string.h>
#include "init.h"
#define WIKI "http\\://gfs.sf.net/wiki/index.php/"

static void output (const char * key, FILE * lang, FILE * dic, FILE * el)
{
  fprintf (lang, "gfs_keyword = \"%s\"\n", key);
  fprintf (dic, "%s\n", key);
  fprintf (el, "\"%s\"\n", key);
}

static void key_value_pair (const char * key, FILE * lang, FILE * dic, FILE * el)
{
  output (key, lang, dic, el);
  /* keywords must start with Gfs */
  g_assert (strstr (key, "Gfs") == key);
  output (&(key[3]), lang, dic, el);
}

int main (int argc, char * argv[])
{
  GtsObjectClass ** klass;

  klass = gfs_classes ();

  FILE * lang = fopen ("gfs.lang", "w");
  FILE * dic  = fopen ("gerris.dic", "w");
  FILE * el   = fopen ("gfs-keywords.el", "w");

  fprintf (lang,
	   "# Language file for source-highlight\n"
	   "# Generated automatically by classes.c\n"
	   "\n");
  fprintf (el, "(defvar gfs-abbrevs '(\n");

  key_value_pair ("GfsDefine", lang, dic, el);
  key_value_pair ("GfsTime", lang, dic, el);
  key_value_pair ("GfsDeferredCompilation", lang, dic, el);
  key_value_pair ("GfsProjectionParams", lang, dic, el);
  key_value_pair ("GfsApproxProjectionParams", lang, dic, el);
  key_value_pair ("GfsPhysicalParams", lang, dic, el);
  key_value_pair ("GfsAdvectionParams", lang, dic, el);

  /* Map module  */
  key_value_pair ("GfsMapProjection", lang, dic, el);

  while (*klass) {
    key_value_pair ((*klass)->info.name, lang, dic, el);
    klass++;
  }
  
  fprintf (lang,
	   "\n"
	   "include \"cpp.lang\"\n"
	   "\n"
	   "comment start \"#\"\n"
	   "\n"
	   "redef preproc = \"C preprocessor command is not compatible with"
	   " the use of # as comment character in GTS\"\n");
  fputs (")\n\"Gerris keywords automatically generated by classes.c.\")\n"
	 "(provide 'gfs-keywords)", 
	 el);
  fclose (lang);
  fclose (dic);
  fclose (el);

  return 0;
}
