#!/bin/sh

# see ../src/darcsversion.sh
darcsversion()
{
    darcs changes --last=1 --xml-output | \
	awk 'BEGIN{RS=" ";FS="="}{if ($1 == "date") print substr($2,4,6);}'
}

usage()
{
	cat <<EOF
Usage: darcs2dist [OPTIONS] PACKAGE REPOSITORY URL

Updates a SourceForge snapshot using the given darcs repository.

EOF
	exit $1
}

if test $# -lt 3; then
	usage 1 1>&2
fi

package=$1
repo=$2
url=$3

wrkdir=`mktemp -d /tmp/darcs2dist.XXXXXX`
cd $wrkdir
if ( darcs get $repo $package && \
     cd $package && \
     version=`darcsversion` && \
     login=`echo $url | awk 'BEGIN{FS=":"}{print $1}'` && \
     dir=`echo $url | awk 'BEGIN{FS=":"}{print $2}'` && \
     sh autogen.sh && \
     make && \
     make dist && \
     tar xzf $package-*.tar.gz && \
     cd  $package-[0-9].[0-9].[0-9] && \
     ./configure && make && cd .. && \
     rm -r -f $package-[0-9].[0-9].[0-9] && tar xzf $package-*.tar.gz && \
     mv $package-[0-9].[0-9].[0-9] $package-snapshot-$version && \
     tar chof - $package-snapshot-$version | gzip --best -c > $package-snapshot-$version.tar.gz && \
     ssh $login "cd $dir/tarballs && rm -f $package-snapshot-*.tar.gz" && \
     scp -q $package-snapshot-$version.tar.gz $url/tarballs/$package-snapshot-$version.tar.gz && \
     ssh $login "cd $dir && ln -s -f tarballs/$package-snapshot-$version.tar.gz $package-snapshot.tar.gz") > msg 2>&1; then
    rm -f msg
    status=0
else
    cat msg
    rm -f msg
    status=1
fi

rm -r -f $wrkdir
exit $status
