#!/bin/sh

usage()
{
	cat <<EOF
Usage: darcs2dist [OPTIONS] PACKAGE REPOSITORY URL

Updates a SourceForge snapshot using the given darcs repository.

EOF
	exit $1
}

if test $# -lt 3; then
	usage 1 1>&2
fi

package=$1
repo=$2
url=$3

curdir=`pwd`
wrkdir=`mktemp -d /tmp/darcs2dist.XXXXXX`
cd $wrkdir

if darcs get $repo $package > msg 2>&1; then
    :
else
    cat msg
    rm -f msg
    exit 1
fi

rm -f msg
cd $package
chmod +x `find . -path ./_darcs -prune -o -type f -name "*.sh" -print`
libtoolize > msg 2>&1
aclocal >> msg 2>&1
autoheader >> msg 2>&1
automake -a >> msg 2>&1
autoconf >> msg 2>&1
./configure >> msg 2>&1
make changelog >> msg 2>&1
if make -k >> msg 2>&1; then
    if make dist >> msg 2>&1; then
	tar xzf $package-*.tar.gz
        mv -f `echo $package-*.tar.gz | sed 's/.tar.gz//'` $package-`date +%y-%m-%d`
        tar cf $package-snapshot.tar $package-`date +%y-%m-%d`
        gzip -f --best $package-snapshot.tar
	scp -q $package-snapshot.tar.gz $url/$package-snapshot.tar.gz
    else
	cat msg
    fi
else
    cat msg
fi
rm -f msg
cd $curdir
rm -r -f $wrkdir
