#!/bin/sh

usage()
{
	cat <<EOF
Usage: darcs2dist [OPTIONS] PACKAGE REPOSITORY URL

Updates a SourceForge snapshot using the given darcs repository.

EOF
	exit $1
}

if test $# -lt 3; then
	usage 1 1>&2
fi

package=$1
repo=$2
url=$3

wrkdir=`mktemp -d /tmp/darcs2dist.XXXXXX`
cd $wrkdir
if ( darcs get $repo $package && \
     cd $package && \
     sh autogen.sh && \
     make dist && \
     scp -q $package-*.tar.gz $url/$package-snapshot.tar.gz ) > msg 2>&1; then
    rm -f msg
    status=0
else
    cat msg
    rm -f msg
    status=1
fi

rm -r -f $wrkdir
exit $status
